"New: Contribution":
  - "**"

"Type: Documentation":
  - docs/**/*

"Type: Infrastructure":
  - any["./*", ".github/**/*", "etc/**/*", "lib/iris/etc/**/*", "requirements/**/*", "tools/**/*"]

"Type: Testing":
  - lib/iris/tests/**/*
