# reference:
#   - https://github.com/actions/cache
#   - https://github.com/actions/checkout
#   - https://github.com/marketplace/actions/setup-miniconda

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
        include:
          - os: ubuntu-latest
            lock-file: requirements/ci/nox.lock/py38-linux-64.lock

    steps:
      - uses: actions/checkout@v2

      - name: Import Iris
        run: |
          pwd
          ls -l
          env | sort

